from selenium.webdriver.common.by import By

class ArticlePageLocators:
    
    # 🧭 Navigation
    ARTICLE_PROFILE_LINK = (By.CSS_SELECTOR, "a.nav-link[href='/@1']")
    ARTICLE_SETTINGS_LINK = (By.CSS_SELECTOR, "a.nav-link[href='/settings']")
    ARTICLE_USER_LINK = (By.CSS_SELECTOR, "a.nav-link[href='/@1']")
    ARTICLE_USER_PROFILE_LINK = (By.CSS_SELECTOR, "li.nav-item a.nav-link[href='/@1']")

    # 📄 Article Preview
    ARTICLE_ARTICLE_DESCRIPTION = (By.CSS_SELECTOR, "a.preview-link p")
    ARTICLE_ARTICLE_META = (By.CSS_SELECTOR, "div.article-meta")
    ARTICLE_ARTICLE_PREVIEW = (By.CSS_SELECTOR, "div.article-preview")
    ARTICLE_ARTICLE_TITLE = (By.CSS_SELECTOR, "a.preview-link h1")
    ARTICLE_ARTICLE_TITLE_BANNER = (By.CSS_SELECTOR, "div.banner h1")
    ARTICLE_DESCRIPTION = (By.CSS_SELECTOR, "a.preview-link p")
    ARTICLE_DESCRIPTIONS = (By.CSS_SELECTOR, "a.preview-link p")
    ARTICLE_POPULAR_TAGS_TITLE = (By.CSS_SELECTOR, "div.sidebar p")
    ARTICLE_PREVIEW = (By.CSS_SELECTOR, "div.article-preview")
    ARTICLE_PREVIEW_DESCRIPTIONS = (By.CSS_SELECTOR, "a.preview-link p")
    ARTICLE_PREVIEW_ITEMS = (By.CSS_SELECTOR, "div.article-preview")
    ARTICLE_PREVIEW_LINK = (By.CSS_SELECTOR, "a.preview-link")
    ARTICLE_PREVIEW_LINKS = (By.CSS_SELECTOR, "a.preview-link")
    ARTICLE_PREVIEW_MESSAGE = (By.CSS_SELECTOR, "div.article-preview")
    ARTICLE_PREVIEW_TAG_LIST = (By.CSS_SELECTOR, "a.preview-link ul.tag-list")
    ARTICLE_TITLE = (By.CSS_SELECTOR, "a.preview-link h1")

    # 🖋 Article Detail
    ARTICLE_ANOTHER_WRITER = (By.CSS_SELECTOR, ".article .article-meta .info a.author")
    ARTICLE_ARTICLE_CONTENT = (By.CSS_SELECTOR, "div.article-content")
    ARTICLE_ARTICLE_PAGE = (By.CSS_SELECTOR, "div.article-page")
    ARTICLE_ARTICLE_TEXT = (By.CSS_SELECTOR, "div.article-content p")
    ARTICLE_AUTHOR_IMAGES = (By.CSS_SELECTOR, "div.article-meta img")
    ARTICLE_AUTHOR_LINK = (By.CSS_SELECTOR, "a.author")
    ARTICLE_AUTHOR_LINKS = (By.CSS_SELECTOR, "a.author")
    ARTICLE_BANNER = (By.CSS_SELECTOR, "div.banner")
    ARTICLE_COMMENT_AUTHOR = (By.CSS_SELECTOR, "a.comment-author")
    ARTICLE_COMMENT_CARD = (By.CSS_SELECTOR, "div.card")
    ARTICLE_COMMENT_CARDS = (By.CSS_SELECTOR, "div.card")
    ARTICLE_COMMENT_DATE = (By.CSS_SELECTOR, "span.date-posted")
    ARTICLE_COMMENT_FORM = (By.CSS_SELECTOR, "form.comment-form")
    ARTICLE_COMMENT_TEXT = (By.CSS_SELECTOR, "p.card-text")
    ARTICLE_COMMENT_TEXTAREA = (By.CSS_SELECTOR, "textarea.form-control")
    ARTICLE_COMPOSE_ICON = (By.CSS_SELECTOR, "i.ion-compose")
    ARTICLE_CONTENT = (By.CSS_SELECTOR, "div.article-content p")
    ARTICLE_DATE = (By.CSS_SELECTOR, "span.date")
    ARTICLE_DATES = (By.CSS_SELECTOR, "span.date")
    ARTICLE_DELETE_COMMENT_BUTTON = (By.CSS_SELECTOR, "span.mod-options i.ion-trash-a")
    ARTICLE_EDIT_PROFILE_BUTTON = (By.CSS_SELECTOR, "a.btn.btn-sm.btn-outline-secondary")
    ARTICLE_FAVORITED_ARTICLES_LINK = (By.CSS_SELECTOR, "a.nav-link[href='/@1/favorites']")
    ARTICLE_FAVORITED_ARTICLES_TAB = (By.CSS_SELECTOR, "a.nav-link[href='/@1/favorites']")
    ARTICLE_FAVORITE_BUTTON = (By.CSS_SELECTOR, "button.btn.btn-sm.btn-outline-primary")
    ARTICLE_FAVORITE_BUTTONS = (By.CSS_SELECTOR, "button.btn-sm")
    ARTICLE_GEAR_ICON = (By.CSS_SELECTOR, "i.ion-gear-a")
    ARTICLE_GLOBAL_FEED_ALT = (By.CSS_SELECTOR, "li.nav-item:nth-child(2) a.nav-link")
    ARTICLE_GLOBAL_FEED_LINK = (By.CSS_SELECTOR, "a.nav-link:not(.active)")
    ARTICLE_HEART_ICONS = (By.CSS_SELECTOR, "i.ion-heart")
    ARTICLE_HOME_PAGE = (By.CSS_SELECTOR, "div.home-page")
    ARTICLE_MY_ARTICLES_LINK = (By.CSS_SELECTOR, "a.nav-link.active[href='/@1']")
    ARTICLE_MY_ARTICLES_TAB = (By.CSS_SELECTOR, "a.nav-link.active[href='/@1']")
    ARTICLE_PAGINATION = (By.CSS_SELECTOR, "ul.pagination")
    ARTICLE_PAGINATION_ITEMS = (By.CSS_SELECTOR, "li.page-item")
    ARTICLE_PAGINATION_LINKS = (By.CSS_SELECTOR, "a.page-link")
    ARTICLE_POPULAR_TAGS_SECTION = (By.CSS_SELECTOR, "div.sidebar")
    ARTICLE_POPULAR_TAGS_TEXT = (By.CSS_SELECTOR, "div.sidebar p")
    ARTICLE_POPULAR_TAG_LINKS = (By.CSS_SELECTOR, "div.sidebar a.tag-default")
   
    ARTICLE_PROFILE_BIO = (By.CSS_SELECTOR, "div.user-info p")
    ARTICLE_PROFILE_USERNAME = (By.CSS_SELECTOR, "div.user-info h4")
    ARTICLE_PROFILE_USER_IMG = (By.CSS_SELECTOR, "img.user-img")
    ARTICLE_ROOT_ELEMENT = (By.ID, "root")
    ARTICLE_SIDEBAR = (By.CSS_SELECTOR, "div.sidebar")
    ARTICLE_TAGS = (By.CSS_SELECTOR, "li.tag-default")
    ARTICLE_TAG_ITEMS = (By.CSS_SELECTOR, "li.tag-default.tag-pill.tag-outline")
    ARTICLE_TAG_PILL = (By.CSS_SELECTOR, "li.tag-default.tag-pill.tag-outline")
    ARTICLE_USERNAME = (By.CSS_SELECTOR, "div.user-info h4")
    ARTICLE_USER_IMG = (By.CSS_SELECTOR, "img.user-img")
    ARTICLE_USER_PIC = (By.CSS_SELECTOR, "img.user-pic")
    ARTICLE_YOUR_FEED_LINK = (By.CSS_SELECTOR, "a.nav-link.active")

    # 🖋 Comment
    ARTICLE_COMMENT_INPUT = (By.CSS_SELECTOR, "textarea.form-control")  # ✅ 댓글 입력창 (이미 유사 항목 있음)
    ARTICLE_COMMENT_LIST = (By.CSS_SELECTOR, "div.card")                # ✅ 댓글 전체 리스트
    ARTICLE_POST_COMMENT_BUTTON = (By.CSS_SELECTOR, "button.btn.btn-sm.btn-primary")  # ✅ 댓글 등록 버튼
    
    ARTICLE_COMMENT_CONTAINER = (By.CSS_SELECTOR, ".col-xs-12.col-md-8.offset-md-2")
    ARTICLE_COMMENT_CARD = (By.CSS_SELECTOR, "div.card.card-block")
    ARTICLE_COMMENT_LAST_CARD = (By.CSS_SELECTOR, "div.card:last-child")
    ARTICLE_COMMENT_PROFILE = (By.CSS_SELECTOR, "a.comment-author img")
    ARTICLE_COMMENT_USERNAME = (By.CSS_SELECTOR, "a.comment-author:nth-of-type(2)")
    ARTICLE_COMMENT_DELETE = (By.CSS_SELECTOR, "i.ion-trash-a")
    ARTICLE_COMMENT_DATE = (By.CSS_SELECTOR, "span.date-posted")
