from selenium.webdriver.common.by import By

class ProfilePage:
    profileNavbarBrand = (By.CSS_SELECTOR, "a.navbar-brand")
    profileHomeLink = (By.CSS_SELECTOR, "a.nav-link[href='/']")
    profileNewPostLink = (By.CSS_SELECTOR, "a.nav-link[href='/editor']")
    profileSettingsLink = (By.CSS_SELECTOR, "a.nav-link[href='/settings']")
    profileUserLink = (By.CSS_SELECTOR, "a.nav-link[href='/@1']")
    profileUserPic = (By.CSS_SELECTOR, "img.user-pic")
    profileUserImg = (By.CSS_SELECTOR, "img.user-img")
    profileUsername = (By.CSS_SELECTOR, "div.user-info h4")
    profileEditSettingsBtn = (By.CSS_SELECTOR, "a.btn.btn-sm.btn-outline-secondary.action-btn")
    profileMyArticlesLink = (By.CSS_SELECTOR, "a.nav-link.active")
    profileFavoritedArticlesLink = (By.CSS_SELECTOR, "a.nav-link[href='/@1/favorites']")
    profileArticlePreview = (By.CSS_SELECTOR, "div.article-preview")
    profileArticleMeta = (By.CSS_SELECTOR, "div.article-meta")
    profileAuthorLink = (By.CSS_SELECTOR, "a.author")
    profileArticleDate = (By.CSS_SELECTOR, "span.date")
    profileFavoriteBtn = (By.CSS_SELECTOR, "button.btn.btn-sm.btn-outline-primary")
    profileFavoriteCount = (By.CSS_SELECTOR, "button.btn.btn-sm.btn-outline-primary")
    profileArticleLink = (By.CSS_SELECTOR, "a.preview-link")
    profileArticleTitle = (By.CSS_SELECTOR, "a.preview-link h1")
    profileArticleDescription = (By.CSS_SELECTOR, "a.preview-link p")
    profileReadMoreLink = (By.CSS_SELECTOR, "a.preview-link span")
    profileTagList = (By.CSS_SELECTOR, "ul.tag-list")## ProfilePage

from selenium.webdriver.common.by import By

class ProfilePage:
    profileNavbarBrand = (By.CSS_SELECTOR, "a.navbar-brand")
    profileHomeLink = (By.CSS_SELECTOR, "a.nav-link[href='/']")
    profileNewPostLink = (By.CSS_SELECTOR, "a.nav-link[href='/editor']")
    profileSettingsLink = (By.CSS_SELECTOR, "a.nav-link[href='/settings']")
    profileUserLink = (By.CSS_SELECTOR, "a.nav-link[href='/@1']")
    profileUserPic = (By.CSS_SELECTOR, "img.user-pic")
    profileUserImg = (By.CSS_SELECTOR, "img.user-img")
    profileUsername = (By.CSS_SELECTOR, "div.user-info h4")
    profileEditSettingsBtn = (By.CSS_SELECTOR, "a.btn-outline-secondary")
    profileMyArticlesLink = (By.CSS_SELECTOR, "a.nav-link[href='/@1']")
    profileFavoritedArticlesLink = (By.CSS_SELECTOR, "a.nav-link[href='/@1/favorites']")
    profileArticlePreview = (By.CSS_SELECTOR, "div.article-preview")
    profileArticleAuthor = (By.CSS_SELECTOR, "a.author")
    profileArticleDate = (By.CSS_SELECTOR, "span.date")
    profileArticleLikeBtn = (By.CSS_SELECTOR, "button.btn-outline-primary")
    profileArticleLikeCount = (By.CSS_SELECTOR, "button.btn-outline-primary")
    profileArticleTitle = (By.CSS_SELECTOR, "a.preview-link h1")
    profileArticleDescription = (By.CSS_SELECTOR, "a.preview-link p")
    profileArticleReadMore = (By.CSS_SELECTOR, "a.preview-link span")
    profileNoArticlesText = (By.CSS_SELECTOR, "div.article-preview")